name: test-python
description: ''
inputs:
  python_version:
    description: ''
    required: true
  pypi_username:
    description: ''
    required: false
    default: ""
  pypi_password:
    description: ''
    required: false
    default: ""
  reports_folder:
    description: ''
    required: false
    default: '.'
  coverage_report:
    description: ''
    required: true
  xunit_report:
    description: ''
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version:  ${{ inputs.python_version }}
        cache: pipenv
    - run: pip3 install pipenv
      shell: bash
    - run: pipenv install --dev
      shell: bash
      env:
        PYPI_USERNAME: ${{ inputs.pypi_username }}
        PYPI_PASSWORD: ${{ inputs.pypi_password }}
    - run: pipenv run pytest --doctest-modules --junitxml=${{ inputs.reports_folder }}/${{ inputs.xunit_report }} --cov=. --cov-report=xml:${{ inputs.reports_folder }}/${{ inputs.coverage_report }} --cov-report=term
      shell: bash